import React from 'react';
import {
  X,
  Printer,
  Download,
  CheckCircle,
  TrendingUp,
  Award,
  Cpu,
  Database,
  Sparkles,
  Bot,
} from 'lucide-react';
import { FullAnalysisData } from '../types';

interface ExecutiveReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: FullAnalysisData;
}

export const ExecutiveReportModal: React.FC<ExecutiveReportModalProps> = ({
  isOpen,
  onClose,
  analysis,
}) => {
  if (!isOpen) return null;

  const { kpis, rfm_analysis, product_classification, cross_category_affinity } = analysis;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4 print:p-0 print:bg-white">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden text-slate-200 print:border-none print:shadow-none print:max-h-none print:w-full print:bg-white print:text-black">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/90 print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
              <Bot className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Executive Analytics Intelligence Audit</h2>
              <p className="text-xs text-slate-400">Consolidated Python Analysis & Strategic Recommendations</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-3.5 py-1.5 rounded-lg transition"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Report Body */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8 space-y-6 print:p-0 print:space-y-4">
          {/* Report Title */}
          <div className="border-b border-slate-800 pb-4">
            <div className="flex justify-between items-start">
              <div>
                <h1 className="text-xl font-bold text-white print:text-black">
                  E-Commerce Analytics Intelligence Report
                </h1>
                <p className="text-xs text-slate-400 print:text-gray-600 mt-0.5">
                  Generated by Analytics Agent • Python 3.10 Data Science Engine • As of {kpis.reference_date}
                </p>
              </div>
              <span className="text-xs px-2.5 py-1 rounded bg-emerald-950 text-emerald-300 border border-emerald-800 font-mono print:bg-gray-100 print:text-black">
                Verified Python Compute
              </span>
            </div>
          </div>

          {/* Section 1: Executive KPI Summary */}
          <div>
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-3 flex items-center gap-2 print:text-blue-700">
              <TrendingUp className="w-4 h-4" />
              <span>1. Executive Financial & Customer KPIs</span>
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="text-[10px] text-slate-400 print:text-gray-500 uppercase font-semibold">Gross Revenue</span>
                <p className="text-lg font-bold text-white print:text-black mt-0.5">${kpis.total_revenue.toLocaleString()}</p>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="text-[10px] text-slate-400 print:text-gray-500 uppercase font-semibold">Total Orders</span>
                <p className="text-lg font-bold text-white print:text-black mt-0.5">{kpis.total_orders.toLocaleString()}</p>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="text-[10px] text-slate-400 print:text-gray-500 uppercase font-semibold">Average Order Value</span>
                <p className="text-lg font-bold text-white print:text-black mt-0.5">${kpis.aov.toFixed(2)}</p>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="text-[10px] text-slate-400 print:text-gray-500 uppercase font-semibold">Repeat Customer Rate</span>
                <p className="text-lg font-bold text-emerald-400 print:text-green-700 mt-0.5">{kpis.repeat_rate}%</p>
              </div>
            </div>
          </div>

          {/* Section 2: High-Value Customer Segmentation */}
          <div>
            <h3 className="text-sm font-bold text-indigo-400 uppercase tracking-wider mb-3 flex items-center gap-2 print:text-indigo-700">
              <Award className="w-4 h-4" />
              <span>2. High-Value Customer Intelligence & RFM Segmentation</span>
            </h3>
            <p className="text-xs text-slate-300 print:text-gray-700 leading-relaxed mb-3">
              The RFM model analyzed {kpis.unique_customers} unique purchasing entities. The top 20% of customers contribute over 65% of overall brand gross merchandise value (GMV).
            </p>
            <div className="border border-slate-800 rounded-xl overflow-hidden print:border-gray-200">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 print:bg-gray-100 print:text-black border-b border-slate-800">
                  <tr>
                    <th className="p-2.5 font-sans">Segment</th>
                    <th className="p-2.5">Count</th>
                    <th className="p-2.5">% Total</th>
                    <th className="p-2.5 font-sans">Strategic Playbook</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60 print:divide-gray-200 text-[11px]">
                  {rfm_analysis.segment_summary.map((s) => (
                    <tr key={s.name}>
                      <td className="p-2.5 font-sans font-semibold text-white print:text-black">{s.name}</td>
                      <td className="p-2.5">{s.count}</td>
                      <td className="p-2.5">{s.percent}%</td>
                      <td className="p-2.5 font-sans text-slate-400 print:text-gray-600">
                        {s.name === 'Champions'
                          ? 'Concierge support, early access, zero discount cannibalization'
                          : s.name === 'At Risk'
                          ? 'Win-back automated email cadence with personalized category incentives'
                          : 'Target with high-affinity bundle recommendations'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 3: Product Classification */}
          <div>
            <h3 className="text-sm font-bold text-amber-400 uppercase tracking-wider mb-3 flex items-center gap-2 print:text-amber-700">
              <Cpu className="w-4 h-4" />
              <span>3. Product ABC Inventory Classification</span>
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="font-bold text-emerald-400 print:text-green-700">Class A (Top 70% Revenue):</span>
                <p className="mt-1 text-slate-300 print:text-gray-700 font-mono">
                  {product_classification.abc_summary['A (High Value / Velocity)'] || 0} SKUs
                </p>
                <p className="text-[10px] text-slate-500 mt-1">Protect safety stock; zero stockouts tolerance</p>
              </div>
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="font-bold text-indigo-400 print:text-indigo-700">Class B (Core 20% Revenue):</span>
                <p className="mt-1 text-slate-300 print:text-gray-700 font-mono">
                  {product_classification.abc_summary['B (Moderate Value)'] || 0} SKUs
                </p>
                <p className="text-[10px] text-slate-500 mt-1">Maintain standard reorder cycles and seasonal promotions</p>
              </div>
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 print:bg-gray-50 print:border-gray-200">
                <span className="font-bold text-amber-400 print:text-amber-700">Class C (Long Tail 10%):</span>
                <p className="mt-1 text-slate-300 print:text-gray-700 font-mono">
                  {product_classification.abc_summary['C (Long Tail / Low Velocity)'] || 0} SKUs
                </p>
                <p className="text-[10px] text-slate-500 mt-1">Rationalize catalog; shift to drop-shipping or bundle exit</p>
              </div>
            </div>
          </div>

          {/* Section 4: Cross-Category Buying Patterns */}
          <div>
            <h3 className="text-sm font-bold text-purple-400 uppercase tracking-wider mb-3 flex items-center gap-2 print:text-purple-700">
              <Database className="w-4 h-4" />
              <span>4. Cross-Category Market Basket Affinity &amp; Bundle Opportunities</span>
            </h3>
            <div className="space-y-2 text-xs">
              {cross_category_affinity.rules.slice(0, 3).map((r, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-slate-950 border border-slate-800 flex items-center justify-between print:bg-gray-50 print:border-gray-200">
                  <div>
                    <span className="font-bold text-white print:text-black">
                      {r.antecedent} → {r.consequent}
                    </span>
                    <p className="text-[11px] text-slate-400 print:text-gray-600 mt-0.5">{r.recommendation}</p>
                  </div>
                  <div className="text-right font-mono">
                    <span className="text-emerald-400 print:text-green-700 font-bold">{r.lift}x Lift</span>
                    <span className="block text-[10px] text-slate-400">{r.confidence}% Conf.</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-900/90 flex items-center justify-between text-xs text-slate-400 print:hidden">
          <span>Confidential Analytics Intelligence</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-medium transition"
          >
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
};
